# Generated by Django 3.2.7 on 2021-09-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Middle', 'Middle'), ('Hard', 'Hard')], max_length=6)),
                ('content', models.TextField(max_length=500)),
                ('answer', models.TextField(max_length=1000)),
            ],
        ),
    ]
